version: "3.9"
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.MAX
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - web-root:/var/www/html
      - ./docker-compose:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nodejs
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email admin@trade-electro.kz --agree-tos --no-eff-email --force-renewal -d api.trade-electro.kz
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /var/www/api.trade-electro.kz/html
      o: bind

networks:
  app-network:
    driver: bridge
